server:
  additionalApplications:
    - name: cluster-config
      namespace: argocd
      project: default
      source:
        repoURL: git@github.com:yotam-halperin/portfolio-charts.git
        targetRevision: HEAD
        path: argocd
        # helm:
        #   values: |
        #     serviceMonitor:
        #       enabled: true # has to be false if you do not have Prometheus already installed
        #     trivy:
        #       ignoreUnfixed: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=False
        automated:
          prune: true
          selfHeal: true