server:
  additionalApplications:
    - name: cluster-config
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/piomin/sample-terraform-kubernetes-argocd.git
        targetRevision: HEAD
        path: argocd/manifests/cluster
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=False
        automated:
          prune: true
          selfHeal: true