server:
  additionalApplications:
    - name: cluster-config
      namespace: argocd
      project: default
      source:
        repoURL: git@github.com:yotam-halperin/portfolio-charts.git
        targetRevision: HEAD
        path: appfiles
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=False
        automated:
          prune: true
          selfHeal: true
    